from enum import StrEnum


class JobStatus(StrEnum):
    RECEIVED = "RECEIVED"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    RETRY_WAITING = "RETRY_WAITING"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class JobPhase(StrEnum):
    RECEIVE_EVENT = "RECEIVE_EVENT"
    LOAD_DOCUMENT = "LOAD_DOCUMENT"
    READ_DOCUMENT_TEXT = "READ_DOCUMENT_TEXT"
    SELECT_TEMPLATE = "SELECT_TEMPLATE"
    EXTRACT_FIELDS = "EXTRACT_FIELDS"
    VALIDATE_RESULTS = "VALIDATE_RESULTS"
    RELOAD_METADATA = "RELOAD_METADATA"
    WRITE_METADATA = "WRITE_METADATA"
    CLEANUP = "CLEANUP"
    COMPLETE = "COMPLETE"


class PhaseStatus(StrEnum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class JobPriority(StrEnum):
    HIGH = "HIGH"
    NORMAL = "NORMAL"
    LOW = "LOW"
