apiVersion: v1
kind: Service
metadata:
  name: {{ include "ezeus.fullname" . }}-api
  labels:
    {{- include "ezeus.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.api.service.port | quote }}
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "ezeus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
