{{- if .Values.ollama.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ezeus.ollamaHost" . }}
  labels:
    {{- include "ezeus.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  type: ClusterIP
  selector:
    {{- include "ezeus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
  ports:
    - name: http
      port: 11434
      targetPort: http
{{- end }}
