{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ezeus.redisHost" . }}
  labels:
    {{- include "ezeus.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  clusterIP: None
  selector:
    {{- include "ezeus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
{{- end }}
